// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkP57InoWvsywszH4Xl-O9SJksSgBIxL8',
    appId: '1:1001313388650:web:a0bcb9b5fae3d22f0ca213',
    messagingSenderId: '1001313388650',
    projectId: 'flutter-demo-175da',
    authDomain: 'flutter-demo-175da.firebaseapp.com',
    storageBucket: 'flutter-demo-175da.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVlx99sYsRC_zaWfZYADeOgpIYMCtc75g',
    appId: '1:1001313388650:android:a4bcc2d54fb315840ca213',
    messagingSenderId: '1001313388650',
    projectId: 'flutter-demo-175da',
    storageBucket: 'flutter-demo-175da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXIfNjyGN-MsYxR4r-98RRp1_0uS3yhMQ',
    appId: '1:1001313388650:ios:73b46dbd2f3f25b60ca213',
    messagingSenderId: '1001313388650',
    projectId: 'flutter-demo-175da',
    storageBucket: 'flutter-demo-175da.appspot.com',
    iosClientId: '1001313388650-9nbsbadpimft23bs7ouaif22o0n5b1vv.apps.googleusercontent.com',
    iosBundleId: 'com.turqosoft.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCXIfNjyGN-MsYxR4r-98RRp1_0uS3yhMQ',
    appId: '1:1001313388650:ios:73b46dbd2f3f25b60ca213',
    messagingSenderId: '1001313388650',
    projectId: 'flutter-demo-175da',
    storageBucket: 'flutter-demo-175da.appspot.com',
    iosClientId: '1001313388650-9nbsbadpimft23bs7ouaif22o0n5b1vv.apps.googleusercontent.com',
    iosBundleId: 'com.turqosoft.mynotes',
  );
}
